### ISSUE TITLE
Not getting images in the frame

### ISSUE THREAD

**Issue by baffioso** [enricofer/go2mapillary#1]
The plugin doesn't show pictures in the frame, when I click the mapillary points on the map. I'm using QGIS 2.12.0 on a windows machine. 

Have also tested on Ubuntu 14.04 with QGIS 2.12.3, where it works fine.

**Comment by enricofer** [comment]
I'm getting the same behaviour on windows Xp and lubuntu 14.04 32 bit. 
The Mapillary javascript widget throws exceptions running in QWebView. This is a big problem, because Qt4 QWebView has been discontinued in favor of Qt5 QtWebEngine but QGis will migrate to Qt5 only with QGis 3.0 with no clear schedule: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/29
Can you report for now your Windows version?

**Comment by baffioso** [comment]
Have been testing on Windows 7 -  64 bit

**Comment by posikifi** [comment]
Didn't work with Ubuntu 2.16.1

Is there any plans to fix this before QGIS # (and QT5)?

**Comment by posikifi** [comment]
Is this really issue qith QWebView? I found that some Mapillary images are shown on and some are not:

- key=XpNKYtcxsRjnnuPHt5jDF: will come to QGIS viewer and also in my Firefox (when openend browser.html with key-parameter.
- key=8X5jPDjyQ1A4ckqfKez2Eg: is not shown either in QGIS viewer, or Firefox.

**Comment by enricofer** [comment]
I'm on holyday till the end of August.
I will have a look. 
The interesting thing is that under 2.16, mapillary viewer no longer throws javascript exceptions.... 
Thanks

**Comment by posikifi** [comment]
Any news about this?

**Comment by enricofer** [comment]
Mapillary client make use webgl which is still unsupported by Qt 4.8 webkit unless not compiled against it. It's a damned complex issue and I would prefer fix it migrating to Qgis 3.0/Qt 5.0.

**Comment by posikifi** [comment]
Ok, maybe it's better to close this. And make plan to create better versio for QGIS 3.0.

**Comment by enricofer** [comment]
@baffioso @posikifi I migrate the plugin to QGIS3 with support to vector tile coverage and mapillary.js
Please check it and report issues or suggestions.
