### ISSUE TITLE
Add warning about qtwebkit

### ISSUE THREAD

**Issue by Gustry** [enricofer/go2mapillary#12]
I got one error while I was installing the plugin. QtWebKit was not found.

I had to do :`sudo apt install python3-pyqt5.qtwebkit` I got QtWebKit already, but the PyQt package. It would be nice to handle this error and display a nice warning with the package name to install.

Thanks

**Comment by enricofer** [comment]
Do you mean a try/except statement during plugin init?

**Comment by enricofer** [comment]
please check https://github.com/enricofer/go2mapillary/commit/c3fa3c4434807fe5359f9fb363fa712085bad127
and report

**Comment by Gustry** [comment]
By reading the code, it looks OK. I will give it a try. Thanks.
