### ISSUE TITLE
cant see imagery

### ISSUE THREAD

**Issue by iamnunocaldeira** [enricofer/go2mapillary#13]
cant load imagery on QGIS 3.0.3. any tips?
![imagem](https://user-images.githubusercontent.com/15980854/41789474-5530735a-7647-11e8-9eb9-6876dadb39fa.png)

**Comment by iamnunocaldeira** [comment]
![imagem](https://user-images.githubusercontent.com/15980854/41789505-78609418-7647-11e8-9ae7-710675942797.png)

**Comment by enricofer** [comment]
Everithing goes fine here. Could you provide instructions to replicate the issue?
