### ISSUE TITLE
issues loading the go2mapillary pluging.

### ISSUE THREAD

**Issue by florisabrams** [enricofer/go2mapillary#15]
When I try to open the plugin following errors shows.

![image](https://user-images.githubusercontent.com/41187146/42724902-3339d15c-877b-11e8-83c1-2805a21d8543.png)

Thanks

flo

**Comment by enricofer** [comment]
for unknown reasons it appears that a python compatibility module 'past' included in 'future' (!) package and that normally comes with python, in your system is not installed: https://pypi.org/project/future/
try to install it manually from terminal:
`pip install future` 
or
`pip3 install future` for python3
https://stackoverflow.com/questions/20082935/how-to-install-pip-for-python-3-on-mac-os-x

**Comment by enricofer** [comment]
Did you solve the issue?

**Comment by florisabrams** [comment]
Deer,

Yes, it worked. Thank you very much for the quick response.


greetings,
flo
