### ISSUE TITLE
Can't see imagery 

### ISSUE THREAD

**Issue by VincentROBBE** [enricofer/go2mapillary#16]
Hi,

Thanks and congratulations for your job !
I am trying to use the plugin with QGIS 3.2, windows 10 but i don't see imagery.
Il seems "Cross origin requests are not supported.", see printscreen 

![capture](https://user-images.githubusercontent.com/5764250/43961914-7f635f80-9cb6-11e8-834c-c1c114aa29e5.PNG)

Bests !

**Comment by cbeddow** [comment]
I have the same issue, Windows 7 64-bit with QGIS 3.2. 

It may be a CORS issue: https://www.thepolyglotdeveloper.com/2014/08/bypass-cors-errors-testing-apis-locally/

**Comment by trandsalu** [comment]
Hi!
I’ve got exactly the same issue – QGIS 3.2.1/Windows 10:
[cid:image001.jpg@01D43A1B.CFE8DE60]
/Toomas

Från: Christopher Beddow <notifications@github.com>
Skickat: den 22 augusti 2018 13:02
Till: enricofer/go2mapillary <go2mapillary@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: Re: [enricofer/go2mapillary] Can't see imagery (#16)


I have the same issue, Windows 7 64-bit with QGIS 3.2.

It may be a CORS issue: https://www.thepolyglotdeveloper.com/2014/08/bypass-cors-errors-testing-apis-locally/

**Comment by enricofer** [comment]
Cross Origin Requests are available when the remote serves the resource with `Access-Control-Allow-Origin: *`  in http response header
In our case, the plugin, reads the browser page in a QWebView (the QT5 web browser widget ) from a local file, that, for security reason should not have a response header (ther is no http server) as you can see from the following image
![screenshot 2018-08-27 11 31 28](https://user-images.githubusercontent.com/7544963/44652657-c195dc00-a9ec-11e8-9b2c-bbb8ac29bf34.png)
Normally, in desktop browsers no header directive results in no CORS and the policy should be activated by an extension.
The plugin uses QT5 Webkit as browser and I can't find any documentation for enabling CORS for local files, but in most QGIS systems, this is not a problem, and executing the html browser page from local file does not throws exception (but I don't know the reason why)
So It should suffits to load html page from a public server for having CORS enabled, so I enabled github pages for this repository and [branched the viewer code](https://github.com/enricofer/go2mapillary/tree/cors) to point the QWebView widget, getting the following http response:
![screenshot 2018-08-27 11 48 44](https://user-images.githubusercontent.com/7544963/44653670-b0020380-a9ef-11e8-8cad-598699ad53e5.png)
Now you can test downloading https://raw.githubusercontent.com/enricofer/go2mapillary/cors/mapillary_viewer.py, substituting the original file in the go2mapillary plugin directory and reloading the plugin to see if imagery is visible. Please check it and let me know

**Comment by trandsalu** [comment]
Yes! Great!
/Toomas

Från: VincentROBBE <notifications@github.com>
Skickat: den 27 augusti 2018 12:25
Till: enricofer/go2mapillary <go2mapillary@noreply.github.com>
Kopia: Toomas Randsalu <Toomas.Randsalu@karlshamn.se>; Comment <comment@noreply.github.com>
Ämne: Re: [enricofer/go2mapillary] Can't see imagery (#16)


It works !
Fabulous !
[image]<https://user-images.githubusercontent.com/5764250/44655086-315b9500-a9f4-11e8-98d5-0c57857544e2.png>

Thanks

**Comment by enricofer** [comment]
Thanks all for submissions.

**Comment by cbeddow** [comment]
What should be the plugin directory? I am having trouble finding it

**Comment by enricofer** [comment]
https://gis.stackexchange.com/questions/274311/qgis-3-plugin-folder-location

**Comment by iamnunocaldeira** [comment]
perfect, finally works on my side with this fix. thanks enricofer

**Comment by andreasneumann** [comment]
Hi @enricofer 
Many thanks for the plugin.

Note that I was also affected by this issue. The green Mapillary layers loaded fine. But I got no images - the panel remained black. After replacing mapillary_viewer.py - everything worked as expected.

Again - many thanks for this useful plugin!
Andreas

**Comment by enricofer** [comment]
I just submitted a new release on repository: http://plugins.qgis.org/plugins/go2mapillary/

**Comment by andreasneumann** [comment]
Excellent - thanks @enricofer 

BTW: I learned about you plugin at the FOSS4G conference in Dar es Salaam. There was a presentation from a Mapillary representative.

**Comment by enricofer** [comment]
I'm happy to know you find it interesting. @cbeddow recently told me about his presentation at foss4g 2018 and I delegate him to show the plugin
Mapillary built a wide tools ecosystem around his imagery service and most of the plugin features come from their vision.
feel free to submit me any issue report or enhancement request.
