### ISSUE TITLE
Circle on null island

### ISSUE THREAD

**Issue by Gustry** [enricofer/go2mapillary#18]
I often have this circle on null island:
![screenshot from 2018-08-27 20-36-58](https://user-images.githubusercontent.com/1609292/44693965-0a738200-aa39-11e8-927c-f8e5130bd205.png)

As soon as I disable the plugin, the circle is gone.

**Comment by enricofer** [comment]
https://github.com/enricofer/go2mapillary/commit/0787c5a9b8f491f1fc76034941f2efa6f84cdca4
