### ISSUE TITLE
The plugin keeps downloading even if I remove the group or close the widget

### ISSUE THREAD

**Issue by Gustry** [enricofer/go2mapillary#19]
Even if I remove the Mapillary widget AND the group in the legend, everytime I zoom in/out, the plugins starts downloading and recreating the group in the legend. So I'm closing QGIS when I want to stop using Mapillary.
There should be a button, maybe use a "setCheckable" on your icon in the toolbar. Checked means that the plugin will download for every new extent.

**Comment by enricofer** [comment]
You should avoid to manually remove mapillary layers. As they are managed by the plugin, some exceptions could be expected.
Indeed your proposal for checkable button is good.
https://github.com/enricofer/go2mapillary/commit/b33680012826b9baa937b7b7995e777a8a12b6c1
