### ISSUE TITLE
API to open a specific Mapillary ID

### ISSUE THREAD

**Issue by Gustry** [enricofer/go2mapillary#20]
I'm the developer of the QuickOSM plugin : https://plugins.qgis.org/plugins/QuickOSM/

According to taginfo, there is, today, 28 000 objects with a mapillary tag : https://taginfo.openstreetmap.org/keys/mapillary

In QGIS 2 with QuickOSM, the plugin is providing some default actions : OSM Browser, Edit in JOSM...
![screenshot from 2018-09-18 21-48-26](https://user-images.githubusercontent.com/1609292/45726360-ec5af680-bb8c-11e8-89d1-be8104ec42d9.png)

I haven't ported yet these actions in QGIS 3. But as I'm going to work again on these actions, I would like to open the mapillary widget from QuickOSM if the "mapillary" field is in the attribute table.
Is there a stable API in go2mapillary to trigger this?
QuickOSM will check if the go2mapillary plugin is active and which version.

**Comment by Gustry** [comment]
It looks so easy. Thanks. I will try. I will reopen if needed.

**Comment by Gustry** [comment]
I'm giving a try tonight about mapillary integration in QuickOSM.

It seems that go2mapillary is not toggled correctly from the python snippet above.
![mapillary](https://user-images.githubusercontent.com/1609292/46912251-4bb6e700-cf3e-11e8-9798-f2914085288c.gif)

* Should go2mapillary download roads and individual points when I activate it from the QuickOSM action? I don't think so, because QuickOSM is requesting only to display the image.
* go2mapillary starts downloading roads and pictures when disabling the toolbar button (on my GIF)
* I'm not sure why I still have a black screen

But we can see, after the download from mapillary that the picture in mapillary is correctly selected from QuickOSM.

You can see my commit above. Can you try your snippet on your side? (when the toolbar button is disabled) Thanks.

**Comment by enricofer** [comment]
I checked that the described method opens the provided image key without trigger the coverage rendering. This happens when you clicked on the icon as it should be.
The problem is that you don't see the related image on dock. Are you able to open the image manually copying and pasting the mapillary field value directly from python console?

**Comment by enricofer** [comment]
Now I see what you mean.
Opening the dock widget by direct plugin api calling confuse checkable action button and the ordinary operativity is inverted. Instead of putting the hand on plugin code to support such external service I would prefer you manually uncheck action:

```
from qgis.utils import plugins
plugins["go2mapillary"].dockwidget.show()
plugins["go2mapillary"].mainAction.setChecked(False) ## uncheck action
plugins["go2mapillary"].viewer.openLocation(mapillary_key)
```

**Comment by Gustry** [comment]
Issue fixed with your commit: https://github.com/enricofer/go2mapillary/commit/fdd5bab492a2e6d1b0a2b4134a91ae4b28c8f4df

Thanks for your inputs
