### ISSUE TITLE
On Qgis 2.14:  QgsDataSourceUri error installing plugin

### ISSUE THREAD

**Issue by marcobra** [enricofer/go2mapillary#3]
Hi Enrico is your plugin for Qgis 2.14.X ?
Reading your github page is not for this release 

My specs:

Versione di QGIS 2.14.11-Essen
QGIS code branch Compilato con Qt 4.8.7

ImportError: cannot import name QgsDataSourceUri

Please manage minor release in source, because it come up as new available plugins in 2.14 .x

Thank
Marco

**Comment by enricofer** [comment]
It is a QGIS3 plugin. 
No hope to see it on QGIS2 due to Qt4 QWebkit Issues.
