### ISSUE TITLE
Right click reveals duplicates of same image key

### ISSUE THREAD

**Issue by cbeddow** [enricofer/go2mapillary#30]
Expected behavior is to see one or multiple different image keys.

Actual behavior is seeing several of the same.

![image](https://user-images.githubusercontent.com/10554922/56746376-5cada400-677c-11e9-8cb5-9e1e2fe6cc33.png)

**Comment by enricofer** [comment]
fixed on master https://github.com/enricofer/go2mapillary/commit/245181fcdac1f5531b6102f142adb47f01eed480
bye
