### ISSUE TITLE
CSS problems

### ISSUE THREAD

**Issue by cbeddow** [enricofer/go2mapillary#31]
Let me know for instructions on troubleshooting this more!

I am see the spatial navigation arrows rendered in the wrong locations, vs where I expect (the forward arrow at center of the screen would be expected).

![image](https://user-images.githubusercontent.com/10554922/56746827-3fc5a080-677d-11e9-81b1-38e009212897.png)

Maybe this can be fixed by updating the MapillaryJS version first?

**Comment by enricofer** [comment]
Arrows are right here.
Maybe a platform or qgis version (qtwebkit) related issue:
![Schermata del 2019-04-27 16-06-20](https://user-images.githubusercontent.com/7544963/56850713-7844b600-6906-11e9-9b7c-c92e69f3306c.png)

**Comment by enricofer** [comment]
Contrary to what I told you, I verified that QT5.9 QtWebkit shipped with QGIS 3.4 now supports recent mapillaryjs releases. So I updated the plugin on master to R 2.18: https://github.com/enricofer/go2mapillary/commit/5e127338eb775f770561702e6b0c4e2f09e8ee66 
Could you give a try?

**Comment by cbeddow** [comment]
I am on 3.2.2 and still this, but I'll update to 3.4 and try more:

![image](https://user-images.githubusercontent.com/10554922/57936310-ebb56400-78c3-11e9-9c92-15c50d05abcb.png)

**Comment by cbeddow** [comment]
3.4.7, much better but still seems to be some distortion:

![image](https://user-images.githubusercontent.com/10554922/57940606-1821ae00-78cd-11e9-93e5-cff036f12fe1.png)

**Comment by enricofer** [comment]
http://plugins.qgis.org/plugins/go2mapillary/version/2.3/
