### ISSUE TITLE
Move from one session to another with the map

### ISSUE THREAD

**Issue by CorentinLemaitre** [enricofer/go2mapillary#32]
Hello,

First things first : thank you for your plugin ! It is really great to show this integration GIS with street level imagery. 
I have a problem to jump to another sequence or another photo after i have used one.
When i first use it, it work well and charge the picture and sequence coverage. Then i can activate it and go to a specific image or sequence. I see the picture well, even in 360 when it is working. I can use every tool and even going to next or previous picture. The problem occures when i want to click in another picture thrue the map view. There is no action of my click, no change in the picture. I try to figure it out but i didn't found any way to make it work. Only solution i start QGIS and pick the rigth sequence first and then move with arrow and so. 

my config : Windows 64 bit QGIS 3.6.0... I hope it is not problem only for me.

**Comment by enricofer** [comment]
Is this a recent issue or there was even before last week update (v2.3)?

Il giorno mer 29 mag 2019, 15:26 Corentin LEMAITRE <notifications@github.com>
ha scritto:

**Comment by CorentinLemaitre** [comment]
I did install it today. Last time i have tried to use it but it was one year ago, and i didn't acheive to make it work.
I have tried harder and it seems that if I activate the tool with the extension menu it work well then.

**Comment by enricofer** [comment]
Everything right here.
Did you enable go2mapillary maptool clicking on dockwidget before browsing on map?
![Screenshot 2019-05-30 11 12 50](https://user-images.githubusercontent.com/7544963/58622726-9407f700-82cc-11e9-98e7-531d76e55c22.png)

**Comment by CorentinLemaitre** [comment]
Yes I do click on it. I will try to make the same mistake again and make screen copy to share it with you.

**Comment by enricofer** [comment]
I have too few elements to guess the issue.
Can you provide further instructions to replicate issue locally?

**Comment by CorentinLemaitre** [comment]
I have try multiple time and I didn't get the problem again on my PC. I then try on another PC just after the installation of the plugin and it didn't happen. So it may be all by my side, i close the issue. sorry about that.

**Comment by enricofer** [comment]
Anyway thanks for submission.

Il giorno gio 6 giu 2019, 17:50 Corentin LEMAITRE <notifications@github.com>
ha scritto:
