### ISSUE TITLE
The plugin is loading the word as soon as I start QGIS

### ISSUE THREAD

**Issue by Gustry** [enricofer/go2mapillary#36]
I started QGIS and the plugin was already trying to download the world.
I couldn't uncheck the mapillary icon.

As you can see, I still got the project list. I didn't click on the mapillary icon.
![Screenshot from 2019-09-20 18-14-24](https://user-images.githubusercontent.com/1609292/65342372-e9954600-dbd2-11e9-83aa-6e8b0500347a.png)

I think the plugin should be disabled by default when we start QGIS (even if it was on when we closed QGIS)

**Comment by enricofer** [comment]
What version are you using? Maybe master from github?

**Comment by enricofer** [comment]
I can't replicate the issue here.
Could you try with master version?
