### ISSUE TITLE
qgisMinimumVersion wrong

### ISSUE THREAD

**Issue by mstuyts** [enricofer/go2mapillary#5]
The qgisMinimumVersion in the metadata should be 2.99 instead of 2.9. 

2.9 makes it show up in QGIS 2.14.x and 2.18.x, while it's a 3.x plugin.

**Comment by enricofer** [comment]
thanks.
https://github.com/enricofer/go2mapillary/commit/6c452b768e8bf8264516f27db33b1e6c690ada48

**Comment by mstuyts** [comment]
As long as older versions of your plugin are available in QGIS plugin repository, they will keep showing up in the QGIS 2.x list of available plugins.  Currently you will find version 1.2 in QGIS 2.18 and version 1.3 in QGIS 2.99 (3.x master).
