### ISSUE TITLE
A minimized dialog is opened at the top left corner when QGIS is launched

### ISSUE THREAD

**Issue by DelazJ** [enricofer/go2mapillary#6]
Hi,
When QGIS is relaunched, a minimized widget of go2mappilary is added in the top left corner of the dialog as shown below. It should stay closed as I chose in the previous session.
 ![image](https://user-images.githubusercontent.com/7983394/33621657-c303e14e-d9eb-11e7-9c5c-94deda99204f.png)
Thanks.

**Comment by enricofer** [comment]
I can't replicate the issue in my ubuntu system.
Could you help me providing some more infos?
Did you reload the plugin before restart QGIS?

**Comment by ArtificialTruth** [comment]
I can reproduce on Windows 7 Enterprise 32bit.
I didn't reload the plugin.

**Comment by DelazJ** [comment]
Sorry @enricofer i forgot to reply (actually i'm not a real user; i was just discovering new plugins). 
Yes, i'm on Windows and did nothing special regarding the plugin after i installed it.

**Comment by enricofer** [comment]
Anyway I can't actually replicate issue so I leave it opened

2017-12-21 7:26 GMT+01:00 Harrissou Sant-anna <notifications@github.com>:
