### ISSUE TITLE
Type error on QgsCoordinateTransform

### ISSUE THREAD

**Issue by enricofer** [enricofer/go2mapillary#9]
Latest QGIS dev introduced a new api break that causes the following exception:

TypeError: QgsCoordinateTransform(): arguments did not match any overloaded call:   overload 1: too many arguments   overload 2: not enough arguments   overload 3: not enough arguments   overload 4: not enough arguments   overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem'

**Comment by enricofer** [comment]
There is an api break on QgsCoordinateTransform. You have to update QGIS dev to solve the issue.

**Comment by alexmodesto73** [comment]
ok

wait..
qgis is already the newest version (1:2.99.0+git20180111+5522f10+14stretch).

**Comment by enricofer** [comment]
Could you send me the exception trace?

**Comment by alexmodesto73** [comment]
Une erreur est survenue lors de l'éxécution du code Python:

TypeError: QgsCoordinateTransform(): arguments did not match any overloaded
call:   overload 1: too many arguments   overload 2: not enough arguments
overload 3: not enough arguments   overload 4: not enough arguments
overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem'

Traceback (most recent call last):
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer.py",
line 430, in run
    self.mapRefreshed()
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer.py",
line 344, in mapRefreshed
    self.coverage.update_coverage()
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_coverage.py",
line 287, in update_coverage
    self.download_tiles()
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_coverage.py",
line 143, in download_tiles
    wgs84_minimum = self.transformToWGS84(QgsPointXY
(ex.xMinimum(),ex.yMinimum()))
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_coverage.py",
line 136, in transformToWGS84
    xform = QgsCoordinateTransform(crsSrc, crsDest)
TypeError: QgsCoordinateTransform(): arguments did not match any
overloaded call:
  overload 1: too many arguments
  overload 2: not enough arguments
  overload 3: not enough arguments
  overload 4: not enough arguments
  overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem'


Version de Python : 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0
20170118]
Version de QGIS : 2.99.0-Master Master, 5522f10

Chemin Python :

   - /usr/share/qgis/python/plugins/processing
   - /usr/share/qgis/python
   - /home/alex/.local/share/QGIS/QGIS3/profiles/default/python
   - /home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins
   - /usr/share/qgis/python/plugins
   - /usr/lib/python35.zip
   - /usr/lib/python3.5
   - /usr/lib/python3.5/plat-x86_64-linux-gnu
   - /usr/lib/python3.5/lib-dynload
   - /usr/local/lib/python3.5/dist-packages
   - /usr/lib/python3/dist-packages
   - /home/alex/.local/share/QGIS/QGIS3/profiles/default/python
   -
   /home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
   -
   /home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/extlibs


---
Alexandre MODESTO


2018-01-13 19:06 GMT+01:00 enrico ferreguti <notifications@github.com>:

**Comment by alexmodesto73** [comment]
a dev qgis told me this:

Check https://github.com/qgis/QGIS/blob/master/doc/api_break.dox#L692
- you need to pass the QgsProject instance to QgsCoordinateTransform
constructors.

---
Alexandre MODESTO


2018-01-13 19:06 GMT+01:00 enrico ferreguti <notifications@github.com>:

**Comment by enricofer** [comment]
in github master version the issue is already fixed: https://github.com/enricofer/go2mapillary/commit/ef0e82829e89cb85c3034078765906e1c6ff092d
I submitted the new plugin release to the repository and I'm still waiting for publishing, but if you need the fix right now you can download master.

**Comment by enricofer** [comment]
just published:

Plugin go2mapillary approval by zimbogisgeek.
The plugin version "[1246] go2mapillary 1.4" is now approved
Link: http://plugins.qgis.org/plugins/go2mapillary/
